# Generated by Django 2.2.1 on 2019-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191003_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
